<?php

namespace Zacksmash\MlbStats\Enums;

enum Positions: string
{
    case PITCHER = 'PITCHER';
    case CATCHER = 'CATCHER';
    case FIRST_BASE = 'FIRST_BASE';
    case SECOND_BASE = 'SECOND_BASE';
    case THIRD_BASE = 'THIRD_BASE';
    case SHORTSTOP = 'SHORTSTOP';
    case LEFT_FIELD = 'LEFT_FIELD';
    case CENTER_FIELD = 'CENTER_FIELD';
    case RIGHT_FIELD = 'RIGHT_FIELD';
    case DESIGNATED_HITTER = 'DESIGNATED_HITTER';
    case PINCH_HITTER = 'PINCH_HITTER';
    case PINCH_RUNNER = 'PINCH_RUNNER';
    case EXTRA_HITTER = 'EXTRA_HITTER';
    case BASE_RUNNER = 'BASE_RUNNER';
    case OUTFIELD = 'OUTFIELD';
    case INFIELD = 'INFIELD';
    case STARTING_PITCHER = 'STARTING_PITCHER';
    case RELIEF_PITCHER = 'RELIEF_PITCHER';
    case CLOSER = 'CLOSER';
    case UTLITY = 'UTLITY';
    case UTLITY_INFIELDER = 'UTLITY_INFIELDER';
    case UTLITY_OUTFIELDER = 'UTLITY_OUTFIELDER';
    case RIGHT_HANDED_PITCHER = 'RIGHT_HANDED_PITCHER';
    case LEFT_HANDED_PITCHER = 'LEFT_HANDED_PITCHER';
    case RIGHT_HANDED_STARTER = 'RIGHT_HANDED_STARTER';
    case LEFT_HANDED_STARTER = 'LEFT_HANDED_STARTER';
    case LEFT_HANDED_RELIEVER = 'LEFT_HANDED_RELIEVER';
    case RIGHT_HANDED_RELIEVER = 'RIGHT_HANDED_RELIEVER';
    case TWO_WAY_PITCHER_INFIELDER = 'TWO_WAY_PITCHER_INFIELDER';
    case TWO_WAY_PITCHER_OUTFIELDER = 'TWO_WAY_PITCHER_OUTFIELDER';
    case TWO_WAY_PITCHER_UTILITY = 'TWO_WAY_PITCHER_UTILITY';
    case TWO_WAY_PLAYER = 'TWO_WAY_PLAYER';
    case BATTER = 'BATTER';
    case UNKNOWN = 'UNKNOWN';
    case RUNNER_ON_FIRST = 'RUNNER_ON_FIRST';
    case RUNNER_ON_SECOND = 'RUNNER_ON_SECOND';
    case RUNNER_ON_THIRD = 'RUNNER_ON_THIRD';

}
