<?php

namespace Zacksmash\MlbStats\Enums;

enum StatTypes: string
{
    case PROJECTED = 'PROJECTED';
    case PROJECTED_ROS = 'PROJECTED_ROS';
    case YEAR_BY_YEAR = 'YEAR_BY_YEAR';
    case YEAR_BY_YEAR_ADVANCED = 'YEAR_BY_YEAR_ADVANCED';
    case YEAR_BY_YEAR_PLAYOFFS = 'YEAR_BY_YEAR_PLAYOFFS';
    case SEASON = 'SEASON';
    case STANDARD = 'STANDARD';
    case ADVANCED = 'ADVANCED';
    case CAREER = 'CAREER';
    case CAREER_REGULAR_SEASON = 'CAREER_REGULAR_SEASON';
    case CAREER_ADVANCED = 'CAREER_ADVANCED';
    case SEASON_ADVANCED = 'SEASON_ADVANCED';
    case CAREER_STAT_SPLITS = 'CAREER_STAT_SPLITS';
    case CAREER_PLAYOFFS = 'CAREER_PLAYOFFS';
    case GAME_LOG = 'GAME_LOG';
    case PLAY_LOG = 'PLAY_LOG';
    case PITCH_LOG = 'PITCH_LOG';
    case METRIC_LOG = 'METRIC_LOG';
    case METRIC_AVERAGES = 'METRIC_AVERAGES';
    case PITCH_ARSENAL = 'PITCH_ARSENAL';
    case OUTS_ABOVE_AVERAGE = 'OUTS_ABOVE_AVERAGE';
    case EXPECTED_STATISTICS = 'EXPECTED_STATISTICS';
    case SABERMETRICS = 'SABERMETRICS';
    case SPRAY_CHART = 'SPRAY_CHART';
    case TRACKING_STATISTICS = 'TRACKING_STATISTICS';
    case VS_PLAYER = 'VS_PLAYER';
    case VS_PLAYER_TOTAL = 'VS_PLAYER_TOTAL';
    case VS_PLAYER_5Y = 'VS_PLAYER_5Y';
    case VS_TEAM = 'VS_TEAM';
    case VS_TEAM_5Y = 'VS_TEAM_5Y';
    case VS_TEAM_TOTAL = 'VS_TEAM_TOTAL';
    case LAST_X_GAMES = 'LAST_X_GAMES';
    case BY_DATE_RANGE = 'BY_DATE_RANGE';
    case BY_DATE_RANGE_ADVANCED = 'BY_DATE_RANGE_ADVANCED';
    case BY_MONTH = 'BY_MONTH';
    case BY_MONTH_PLAYOFFS = 'BY_MONTH_PLAYOFFS';
    case BY_DAY_OF_WEEK = 'BY_DAY_OF_WEEK';
    case BY_DAY_OF_WEEK_PLAYOFFS = 'BY_DAY_OF_WEEK_PLAYOFFS';
    case HOME_AND_AWAY = 'HOME_AND_AWAY';
    case HOME_AND_AWAY_PLAYOFFS = 'HOME_AND_AWAY_PLAYOFFS';
    case WIN_LOSS = 'WIN_LOSS';
    case WIN_LOSS_PLAYOFFS = 'WIN_LOSS_PLAYOFFS';
    case RANKINGS = 'RANKINGS';
    case RANKINGS_BY_YEAR = 'RANKINGS_BY_YEAR';
    case STATS_SINGLE_SEASON = 'STATS_SINGLE_SEASON';
    case STATS_SINGLE_SEASON_ADVANCED = 'STATS_SINGLE_SEASON_ADVANCED';
    case HOT_COLD_ZONES = 'HOT_COLD_ZONES';
    case AVAILABLE_STATS = 'AVAILABLE_STATS';
    case OPPONENTS_FACED = 'OPPONENTS_FACED';
    case GAME_TYPE_STATS = 'GAME_TYPE_STATS';
    case FIRST_YEAR_STATS = 'FIRST_YEAR_STATS';
    case LAST_YEAR_STATS = 'LAST_YEAR_STATS';
    case STAT_SPLITS = 'STAT_SPLITS';
    case STAT_SPLITS_ADVANCED = 'STAT_SPLITS_ADVANCED';
    case AT_GAME_START = 'AT_GAME_START';
    case VS_OPPONENTS = 'VS_OPPONENTS';
    case SABERMETRICS_MULTI_TEAM = 'SABERMETRICS_MULTI_TEAM';

}
