<?php

namespace Zacksmash\MlbStats\Facades;

use Illuminate\Support\Facades\Facade;

/**
 * @see \Zacksmash\MlbStats\MlbStats
 *
 * @method static \Zacksmash\MlbStats\Resources\AchievementStatuses achievementStatuses()
 * @method static \Zacksmash\MlbStats\Resources\AllSportBallot allSportBallot(int|string $sportId = 1)
 * @method static \Zacksmash\MlbStats\Resources\Attendance attendance()
 * @method static \Zacksmash\MlbStats\Resources\Award award(string $awardId)
 * @method static \Zacksmash\MlbStats\Resources\AwardRecipients awardRecipients(string $awardId)
 * @method static \Zacksmash\MlbStats\Resources\Awards awards()
 * @method static \Zacksmash\MlbStats\Resources\BaseballStats baseballStats()
 * @method static \Zacksmash\MlbStats\Resources\BatTrackingByPlay batTrackingByPlay(int|string $gamePk, string $playId)
 * @method static \Zacksmash\MlbStats\Resources\BroadcastAvailability broadcastAvailability()
 * @method static \Zacksmash\MlbStats\Resources\Broadcasters broadcasters()
 * @method static \Zacksmash\MlbStats\Resources\Broadcasts broadcasts()
 * @method static \Zacksmash\MlbStats\Resources\CoachingVideoTypes coachingVideoTypes()
 * @method static \Zacksmash\MlbStats\Resources\Conference conference(int|string $conferenceId)
 * @method static \Zacksmash\MlbStats\Resources\Conferences conferences()
 * @method static \Zacksmash\MlbStats\Resources\Division division(int|string $divisionId)
 * @method static \Zacksmash\MlbStats\Resources\Divisions divisions()
 * @method static \Zacksmash\MlbStats\Resources\Draft draft(int|string|null $year = null)
 * @method static \Zacksmash\MlbStats\Resources\DraftLatest draftLatest(int|string $year)
 * @method static \Zacksmash\MlbStats\Resources\DraftProspects draftProspects(int|string $year)
 * @method static \Zacksmash\MlbStats\Resources\EventStatuses eventStatuses()
 * @method static \Zacksmash\MlbStats\Resources\EventTypes eventTypes()
 * @method static \Zacksmash\MlbStats\Resources\FielderDetailTypes fielderDetailTypes()
 * @method static \Zacksmash\MlbStats\Resources\FreeGameTypes freeGameTypes()
 * @method static \Zacksmash\MlbStats\Resources\GameAnalytics gameAnalytics()
 * @method static \Zacksmash\MlbStats\Resources\GameAnalyticsGuids gameAnalyticsGuids()
 * @method static \Zacksmash\MlbStats\Resources\GameBoxscore gameBoxscore(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\GameChanges gameChanges()
 * @method static \Zacksmash\MlbStats\Resources\GameColorFeed gameColorFeed(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\GameColorFeedTimestamps gameColorFeedTimestamps(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\GameContent gameContent(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\GameContextMetrics gameContextMetrics(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\GameGuidAnalytics gameGuidAnalytics(int|string $gamePk, string $guid)
 * @method static \Zacksmash\MlbStats\Resources\GameGuidContextMetrics gameGuidContextMetrics(int|string $gamePk, string $guid)
 * @method static \Zacksmash\MlbStats\Resources\GameGuidContextMetricsAverages gameGuidContextMetricsAverages(int|string $gamePk, string $guid)
 * @method static \Zacksmash\MlbStats\Resources\GameGuidHomeRunBallparks gameGuidHomeRunBallparks(int|string $gamePk, string $guid)
 * @method static \Zacksmash\MlbStats\Resources\GameGuids gameGuids(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\GameLastPitch gameLastPitch()
 * @method static \Zacksmash\MlbStats\Resources\GameLinescore gameLinescore(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\GameLiveFeed gameLiveFeed(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\GameLiveFeedDiffPatch gameLiveFeedDiffPatch(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\GameLiveFeedTimestamps gameLiveFeedTimestamps(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\GameMetrics gameMetrics(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\GamePace gamePace()
 * @method static \Zacksmash\MlbStats\Resources\GamePlayBiomechanics gamePlayBiomechanics(int|string $gamePk, string $playId, int|string $positionId)
 * @method static \Zacksmash\MlbStats\Resources\GamePlayByPlay gamePlayByPlay(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\GamePlaySkeletalChunked gamePlaySkeletalChunked(int|string $gamePk, string $playId)
 * @method static \Zacksmash\MlbStats\Resources\GamePlaySkeletalFiles gamePlaySkeletalFiles(int|string $gamePk, string $playId)
 * @method static \Zacksmash\MlbStats\Resources\GameStatuses gameStatuses()
 * @method static \Zacksmash\MlbStats\Resources\GameTypes gameTypes()
 * @method static \Zacksmash\MlbStats\Resources\GameWinProbability gameWinProbability(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\GamedayTypes gamedayTypes()
 * @method static \Zacksmash\MlbStats\Resources\GroupByTypes groupByTypes()
 * @method static \Zacksmash\MlbStats\Resources\HighLow highLow(string $highLowType)
 * @method static \Zacksmash\MlbStats\Resources\HighLowTypes highLowTypes()
 * @method static \Zacksmash\MlbStats\Resources\HitTrajectories hitTrajectories()
 * @method static \Zacksmash\MlbStats\Resources\HomeRunDerby homeRunDerby()
 * @method static \Zacksmash\MlbStats\Resources\HomeRunDerbyBracket homeRunDerbyBracket()
 * @method static \Zacksmash\MlbStats\Resources\HomeRunDerbyMixed homeRunDerbyMixed(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\HomeRunDerbyPool homeRunDerbyPool(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\HomeRunDerbyGame homeRunDerbyGame(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\HomeRunDerbyGameBracket homeRunDerbyGameBracket(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\HomeRunDerbyGameMixed homeRunDerbyGameMixed(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\HomeRunDerbyGamePool homeRunDerbyGamePool(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\JobTypes jobTypes()
 * @method static \Zacksmash\MlbStats\Resources\Jobs jobs()
 * @method static \Zacksmash\MlbStats\Resources\JobsDatacasters jobsDatacasters()
 * @method static \Zacksmash\MlbStats\Resources\JobsOfficialScorers jobsOfficialScorers()
 * @method static \Zacksmash\MlbStats\Resources\JobsUmpireSchedule jobsUmpireSchedule(int|string $umpireId)
 * @method static \Zacksmash\MlbStats\Resources\JobsUmpires jobsUmpires()
 * @method static \Zacksmash\MlbStats\Resources\Languages languages()
 * @method static \Zacksmash\MlbStats\Resources\League league(int|string $leagueId)
 * @method static \Zacksmash\MlbStats\Resources\LeagueAllStarBallot leagueAllStarBallot(int|string $leagueId)
 * @method static \Zacksmash\MlbStats\Resources\LeagueAllStarFinalVote leagueAllStarFinalVote(int|string $leagueId)
 * @method static \Zacksmash\MlbStats\Resources\LeagueAllStarWriteIns leagueAllStarWriteIns(int|string $leagueId)
 * @method static \Zacksmash\MlbStats\Resources\LeagueLeaderTypes leagueLeaderTypes()
 * @method static \Zacksmash\MlbStats\Resources\Leagues leagues()
 * @method static \Zacksmash\MlbStats\Resources\LeaguesAllStarBallot leaguesAllStarBallot()
 * @method static \Zacksmash\MlbStats\Resources\LogicalEvents logicalEvents()
 * @method static \Zacksmash\MlbStats\Resources\LookupValues lookupValues()
 * @method static \Zacksmash\MlbStats\Resources\MediaStateTypes mediaStateTypes()
 * @method static \Zacksmash\MlbStats\Resources\Metrics metrics()
 * @method static \Zacksmash\MlbStats\Resources\MilestoneDurations milestoneDurations()
 * @method static \Zacksmash\MlbStats\Resources\MilestoneLookups milestoneLookups()
 * @method static \Zacksmash\MlbStats\Resources\MilestoneStatistics milestoneStatistics()
 * @method static \Zacksmash\MlbStats\Resources\MilestoneTypes milestoneTypes()
 * @method static \Zacksmash\MlbStats\Resources\Milestones milestones()
 * @method static \Zacksmash\MlbStats\Resources\MoundVisitTypes moundVisitTypes()
 * @method static \Zacksmash\MlbStats\Resources\People people()
 * @method static \Zacksmash\MlbStats\Resources\PeopleSearch peopleSearch()
 * @method static \Zacksmash\MlbStats\Resources\PerformerTypes performerTypes()
 * @method static \Zacksmash\MlbStats\Resources\Person person(int|string $personId)
 * @method static \Zacksmash\MlbStats\Resources\PersonAward personAward(int|string $personId)
 * @method static \Zacksmash\MlbStats\Resources\PersonStatsMetrics personStatsMetrics(int|string $personId)
 * @method static \Zacksmash\MlbStats\Resources\PitchCodes pitchCodes()
 * @method static \Zacksmash\MlbStats\Resources\PitchTypes pitchTypes()
 * @method static \Zacksmash\MlbStats\Resources\Platforms platforms()
 * @method static \Zacksmash\MlbStats\Resources\PlayerChanges playerChanges()
 * @method static \Zacksmash\MlbStats\Resources\PlayerGameStats playerGameStats(int|string $playerId, int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\PlayerFreeAgents playerFreeAgents()
 * @method static \Zacksmash\MlbStats\Resources\PlayerStatusCodes playerStatusCodes()
 * @method static \Zacksmash\MlbStats\Resources\PlayerStats playerStats(int|string $personId)
 * @method static \Zacksmash\MlbStats\Resources\Positions positions()
 * @method static \Zacksmash\MlbStats\Resources\PropsPredictions propsPredictions()
 * @method static \Zacksmash\MlbStats\Resources\PropsPredictionsAdjust propsPredictionsAdjust()
 * @method static \Zacksmash\MlbStats\Resources\ReviewReasons reviewReasons()
 * @method static \Zacksmash\MlbStats\Resources\Reviews reviews()
 * @method static \Zacksmash\MlbStats\Resources\RoofTypes roofTypes()
 * @method static \Zacksmash\MlbStats\Resources\RosterTypes rosterTypes()
 * @method static \Zacksmash\MlbStats\Resources\RuleSettings ruleSettings()
 * @method static \Zacksmash\MlbStats\Resources\RunnerDetailTypes runnerDetailTypes()
 * @method static \Zacksmash\MlbStats\Resources\Schedule schedule()
 * @method static \Zacksmash\MlbStats\Resources\ScheduleEventTypes scheduleEventTypes()
 * @method static \Zacksmash\MlbStats\Resources\SchedulePostSeasonTuneIn schedulePostSeasonTuneIn()
 * @method static \Zacksmash\MlbStats\Resources\SchedulePostseason schedulePostseason()
 * @method static \Zacksmash\MlbStats\Resources\SchedulePostseasonSeries schedulePostseasonSeries()
 * @method static \Zacksmash\MlbStats\Resources\ScheduleTiedGames scheduleTiedGames()
 * @method static \Zacksmash\MlbStats\Resources\ScheduleTrackingEvents scheduleTrackingEvents()
 * @method static \Zacksmash\MlbStats\Resources\ScheduleType scheduleType(string $scheduleType)
 * @method static \Zacksmash\MlbStats\Resources\ScheduleTypes scheduleTypes()
 * @method static \Zacksmash\MlbStats\Resources\Season season(string $seasonId)
 * @method static \Zacksmash\MlbStats\Resources\Seasons seasons()
 * @method static \Zacksmash\MlbStats\Resources\SeasonsAll seasonsAll()
 * @method static \Zacksmash\MlbStats\Resources\SitCodes sitCodes()
 * @method static \Zacksmash\MlbStats\Resources\Sky sky()
 * @method static \Zacksmash\MlbStats\Resources\SortModifiers sortModifiers()
 * @method static \Zacksmash\MlbStats\Resources\Sport sport(int|string $sportId)
 * @method static \Zacksmash\MlbStats\Resources\SportPlayers sportPlayers(int|string $sportId)
 * @method static \Zacksmash\MlbStats\Resources\Sports sports(int|string $sportId)
 * @method static \Zacksmash\MlbStats\Resources\Standings standings(string $standingsType)
 * @method static \Zacksmash\MlbStats\Resources\StandingsTypes standingsTypes()
 * @method static \Zacksmash\MlbStats\Resources\StatFields statFields()
 * @method static \Zacksmash\MlbStats\Resources\StatGroups statGroups()
 * @method static \Zacksmash\MlbStats\Resources\StatTypes statTypes()
 * @method static \Zacksmash\MlbStats\Resources\StatcastPositionTypes statcastPositionTypes()
 * @method static \Zacksmash\MlbStats\Resources\Stats stats()
 * @method static \Zacksmash\MlbStats\Resources\StatsGrouped statsGrouped()
 * @method static \Zacksmash\MlbStats\Resources\StatsLeaders statsLeaders()
 * @method static \Zacksmash\MlbStats\Resources\StatsMetrics statsMetrics()
 * @method static \Zacksmash\MlbStats\Resources\StatsOutsAboveAverage statsOutsAboveAverage()
 * @method static \Zacksmash\MlbStats\Resources\StatsSearch statsSearch()
 * @method static \Zacksmash\MlbStats\Resources\StatsSearchBeast statsSearchBeast()
 * @method static \Zacksmash\MlbStats\Resources\StatsSearchConfig statsSearchConfig()
 * @method static \Zacksmash\MlbStats\Resources\StatsSearchGroupByTypes statsSearchGroupByTypes()
 * @method static \Zacksmash\MlbStats\Resources\StatsSearchParams statsSearchParams()
 * @method static \Zacksmash\MlbStats\Resources\StatsSprayChart statsSprayChart()
 * @method static \Zacksmash\MlbStats\Resources\StatsStolenBaseProbability statsStolenBaseProbability()
 * @method static \Zacksmash\MlbStats\Resources\StreakTypes streakTypes()
 * @method static \Zacksmash\MlbStats\Resources\Streaks streaks()
 * @method static \Zacksmash\MlbStats\Resources\Team team(int|string $teamId)
 * @method static \Zacksmash\MlbStats\Resources\TeamAffiliates teamAffiliates(int|string $teamId)
 * @method static \Zacksmash\MlbStats\Resources\TeamAlumni teamAlumni(int|string $teamId)
 * @method static \Zacksmash\MlbStats\Resources\TeamCoaches teamCoaches(int|string $teamId)
 * @method static \Zacksmash\MlbStats\Resources\TeamHistory teamHistory(int|string $teamId)
 * @method static \Zacksmash\MlbStats\Resources\TeamLeaders teamLeaders(int|string $teamId)
 * @method static \Zacksmash\MlbStats\Resources\TeamPersonnel teamPersonnel(int|string $teamId)
 * @method static \Zacksmash\MlbStats\Resources\TeamRoster teamRoster(int|string $teamId)
 * @method static \Zacksmash\MlbStats\Resources\TeamRosterType teamRosterType(int|string $teamId, string $rosterType)
 * @method static \Zacksmash\MlbStats\Resources\TeamStats teamStats(int|string $teamId)
 * @method static \Zacksmash\MlbStats\Resources\Teams teams()
 * @method static \Zacksmash\MlbStats\Resources\TeamsAffiliates teamsAffiliates()
 * @method static \Zacksmash\MlbStats\Resources\TeamsHistory teamsHistory()
 * @method static \Zacksmash\MlbStats\Resources\TeamsStats teamsStats()
 * @method static \Zacksmash\MlbStats\Resources\TeamsStatsLeaders teamsStatsLeaders()
 * @method static \Zacksmash\MlbStats\Resources\TrackingSoftwareVersions trackingSoftwareVersions()
 * @method static \Zacksmash\MlbStats\Resources\TrackingSystemOwners trackingSystemOwners()
 * @method static \Zacksmash\MlbStats\Resources\TrackingVendors trackingVendors()
 * @method static \Zacksmash\MlbStats\Resources\TrackingVersions trackingVersions()
 * @method static \Zacksmash\MlbStats\Resources\TransactionTypes transactionTypes()
 * @method static \Zacksmash\MlbStats\Resources\Transactions transactions()
 * @method static \Zacksmash\MlbStats\Resources\UniformsByGame uniformsByGame()
 * @method static \Zacksmash\MlbStats\Resources\UniformsByTeam uniformsByTeam()
 * @method static \Zacksmash\MlbStats\Resources\Venue venue(int|string $venueId)
 * @method static \Zacksmash\MlbStats\Resources\Venues venues()
 * @method static \Zacksmash\MlbStats\Resources\VideoResolutionTypes videoResolutionTypes()
 * @method static \Zacksmash\MlbStats\Resources\ViolationTypes violationTypes()
 * @method static \Zacksmash\MlbStats\Resources\WeatherBasic weatherBasic(int|string $venueId)
 * @method static \Zacksmash\MlbStats\Resources\WeatherByPlay weatherByPlay(int|string $gamePk, string $playId)
 * @method static \Zacksmash\MlbStats\Resources\WeatherForecast weatherForecast(int|string $gamePk, string $roofType)
 * @method static \Zacksmash\MlbStats\Resources\WeatherFull weatherFull(int|string $venueId)
 * @method static \Zacksmash\MlbStats\Resources\WeatherTrajectoryConfidences weatherTrajectoryConfidences()
 * @method static \Zacksmash\MlbStats\Resources\WindDirection windDirection()
 */
class MlbStats extends Facade
{
    protected static function getFacadeAccessor(): string
    {
        return \Zacksmash\MlbStats\MlbStats::class;
    }
}
