<?php

namespace Zacksmash\MlbStats\Facades;

use Illuminate\Support\Facades\Facade;

/**
 * @method static \Zacksmash\MlbStats\Resources\Attendance attendance()
 * @method static \Zacksmash\MlbStats\Resources\AwardRecipients awardRecipients(int|string $awardId)
 * @method static \Zacksmash\MlbStats\Resources\Conference conference(int|string $conferenceId)
 * @method static \Zacksmash\MlbStats\Resources\Conferences conferences()
 * @method static \Zacksmash\MlbStats\Resources\Divisions divisions()
 * @method static \Zacksmash\MlbStats\Resources\Draft draft(string $year)
 * @method static \Zacksmash\MlbStats\Resources\DraftLatest draftLatest(string $year)
 * @method static \Zacksmash\MlbStats\Resources\DraftProspects draftProspects(string $year)
 * @method static \Zacksmash\MlbStats\Resources\GameAnalyticsGame gameAnalyticsGame()
 * @method static \Zacksmash\MlbStats\Resources\GameAnalyticsGuids gameAnalyticsGuids()
 * @method static \Zacksmash\MlbStats\Resources\GameBoxscore gameBoxscore(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\GameChanges gameChanges()
 * @method static \Zacksmash\MlbStats\Resources\GameColorFeed gameColorFeed(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\GameColorFeedDiffPatch gameColorFeedDiffPatch(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\GameColorFeedTimestamps gameColorFeedTimestamps(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\GameContent gameContent(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\GameContextMetrics gameContextMetrics(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\GameGuidAnalytics gameGuidAnalytics(int|string $gamePk, string $guid)
 * @method static \Zacksmash\MlbStats\Resources\GameGuidContextMetricsAverages gameGuidContextMetricsAverages(int|string $gamePk, string $guid)
 * @method static \Zacksmash\MlbStats\Resources\GameGuids gameGuids(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\GameLinescore gameLinescore(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\GameLiveFeed gameLiveFeed(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\GameLiveFeedDiffPatch gameLiveFeedDiffPatch(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\GameLiveFeedTimestamps gameLiveFeedTimestamps(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\GamePace gamePace()
 * @method static \Zacksmash\MlbStats\Resources\GamePlayByPlay gamePlayByPlay(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\GameWinProbability gameWinProbability(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\HighLow highLow(\Zacksmash\MlbStats\Enums\HighLowOrgType|string $orgType)
 * @method static \Zacksmash\MlbStats\Resources\HomeRunDerby homeRunDerby(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\HomeRunDerbyBracket homeRunDerbyBracket(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\HomeRunDerbyPool homeRunDerbyPool(int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\Jobs jobs()
 * @method static \Zacksmash\MlbStats\Resources\JobsDatacasters jobsDatacasters()
 * @method static \Zacksmash\MlbStats\Resources\JobsOfficialScorers jobsOfficialScorers()
 * @method static \Zacksmash\MlbStats\Resources\JobsUmpireGames jobsUmpireGames(int|string $umpireId)
 * @method static \Zacksmash\MlbStats\Resources\JobsUmpires jobsUmpires()
 * @method static \Zacksmash\MlbStats\Resources\League league()
 * @method static \Zacksmash\MlbStats\Resources\LeagueAllStarBallot leagueAllStarBallot(int|string $leagueId)
 * @method static \Zacksmash\MlbStats\Resources\LeagueAllStarFinalVote leagueAllStarFinalVote(int|string $leagueId)
 * @method static \Zacksmash\MlbStats\Resources\LeagueAllStarWriteIns leagueAllStarWriteIns(int|string $leagueId)
 * @method static \Zacksmash\MlbStats\Resources\People people()
 * @method static \Zacksmash\MlbStats\Resources\PeopleFreeAgents peopleFreeAgents()
 * @method static \Zacksmash\MlbStats\Resources\Person person(int|string $personId)
 * @method static \Zacksmash\MlbStats\Resources\PersonCurrentGameStats personCurrentGameStats(int|string $personId)
 * @method static \Zacksmash\MlbStats\Resources\PersonGameStats personGameStats(int|string $personId, int|string $gamePk)
 * @method static \Zacksmash\MlbStats\Resources\Schedule schedule()
 * @method static \Zacksmash\MlbStats\Resources\ScheduleGamesTied scheduleGamesTied()
 * @method static \Zacksmash\MlbStats\Resources\SchedulePostseason schedulePostseason()
 * @method static \Zacksmash\MlbStats\Resources\SchedulePostseasonSeries schedulePostseasonSeries()
 * @method static \Zacksmash\MlbStats\Resources\SchedulePostseasonTuneIn schedulePostseasonTuneIn()
 * @method static \Zacksmash\MlbStats\Resources\Season season(int|string $seasonId)
 * @method static \Zacksmash\MlbStats\Resources\Seasons seasons()
 * @method static \Zacksmash\MlbStats\Resources\SeasonsAll seasonsAll()
 * @method static \Zacksmash\MlbStats\Resources\Sport sport(int|string $sportId)
 * @method static \Zacksmash\MlbStats\Resources\SportPlayers sportPlayers(int|string $sportId)
 * @method static \Zacksmash\MlbStats\Resources\Sports sports()
 * @method static \Zacksmash\MlbStats\Resources\Standings standings()
 * @method static \Zacksmash\MlbStats\Resources\Stats stats()
 * @method static \Zacksmash\MlbStats\Resources\StatsLeaders statsLeaders()
 * @method static \Zacksmash\MlbStats\Resources\StatsMetrics statsMetrics()
 * @method static \Zacksmash\MlbStats\Resources\StatsStreaks statsStreaks()
 * @method static \Zacksmash\MlbStats\Resources\Team team(int|string $teamId)
 * @method static \Zacksmash\MlbStats\Resources\TeamAffiliates teamAffiliates(int|string $teamId)
 * @method static \Zacksmash\MlbStats\Resources\TeamAlumni teamAlumni(int|string $teamId)
 * @method static \Zacksmash\MlbStats\Resources\TeamCoaches teamCoaches(int|string $teamId)
 * @method static \Zacksmash\MlbStats\Resources\TeamLeaders teamLeaders(int|string $teamId)
 * @method static \Zacksmash\MlbStats\Resources\TeamPersonnel teamPersonnel(int|string $teamId)
 * @method static \Zacksmash\MlbStats\Resources\TeamRoster teamRoster(int|string $teamId)
 * @method static \Zacksmash\MlbStats\Resources\TeamRosterType teamRosterType(int|string $teamId, string $rosterType)
 * @method static \Zacksmash\MlbStats\Resources\Teams teams()
 * @method static \Zacksmash\MlbStats\Resources\TeamsAffiliates teamsAffiliates()
 * @method static \Zacksmash\MlbStats\Resources\TeamsHistory teamsHistory()
 * @method static \Zacksmash\MlbStats\Resources\TeamsStats teamsStats()
 * @method static \Zacksmash\MlbStats\Resources\TeamsStatsLeaders teamsStatsLeaders()
 * @method static \Zacksmash\MlbStats\Resources\TeamStats teamStats(int|string $teamId)
 * @method static \Zacksmash\MlbStats\Resources\Venues venues()
 *
 * Config Resources
 * @method static \Zacksmash\MlbStats\Resources\Config\Awards awards()
 * @method static \Zacksmash\MlbStats\Resources\Config\BaseballStats baseballStats()
 * @method static \Zacksmash\MlbStats\Resources\Config\EventTypes eventTypes()
 * @method static \Zacksmash\MlbStats\Resources\Config\FielderDetailTypes fielderDetailTypes()
 * @method static \Zacksmash\MlbStats\Resources\Config\GameStatus gameStatus()
 * @method static \Zacksmash\MlbStats\Resources\Config\GameTypes gameTypes()
 * @method static \Zacksmash\MlbStats\Resources\Config\HighLowTypes highLowTypes()
 * @method static \Zacksmash\MlbStats\Resources\Config\HitTrajectories hitTrajectories()
 * @method static \Zacksmash\MlbStats\Resources\Config\JobTypes jobTypes()
 * @method static \Zacksmash\MlbStats\Resources\Config\Languages languages()
 * @method static \Zacksmash\MlbStats\Resources\Config\LeagueLeaderTypes leagueLeaderTypes()
 * @method static \Zacksmash\MlbStats\Resources\Config\LogicalEvents logicalEvents()
 * @method static \Zacksmash\MlbStats\Resources\Config\Metrics metrics()
 * @method static \Zacksmash\MlbStats\Resources\Config\PitchCodes pitchCodes()
 * @method static \Zacksmash\MlbStats\Resources\Config\PitchTypes pitchTypes()
 * @method static \Zacksmash\MlbStats\Resources\Config\PlayerStatusCodes playerStatusCodes()
 * @method static \Zacksmash\MlbStats\Resources\Config\Positions positions()
 * @method static \Zacksmash\MlbStats\Resources\Config\ReviewReasons reviewReasons()
 * @method static \Zacksmash\MlbStats\Resources\Config\RosterTypes rosterTypes()
 * @method static \Zacksmash\MlbStats\Resources\Config\RunnerDetailTypes runnerDetailTypes()
 * @method static \Zacksmash\MlbStats\Resources\Config\ScheduleEventTypes scheduleEventTypes()
 * @method static \Zacksmash\MlbStats\Resources\Config\SituationCodes situationCodes()
 * @method static \Zacksmash\MlbStats\Resources\Config\Sky sky()
 * @method static \Zacksmash\MlbStats\Resources\Config\StandingsTypes standingsTypes()
 * @method static \Zacksmash\MlbStats\Resources\Config\StatGroups statGroups()
 * @method static \Zacksmash\MlbStats\Resources\Config\StatTypes statTypes()
 * @method static \Zacksmash\MlbStats\Resources\Config\WindDirection windDirection()
 *
 * @see \Zacksmash\MlbStats\MlbStats
 */
class MlbStats extends Facade
{
    protected static function getFacadeAccessor(): string
    {
        return \Zacksmash\MlbStats\MlbStats::class;
    }
}
